version: "3.9"

volumes:
  tmp-files:
    name: tfa-tmp-files

networks:
  tfa-servers:
    name: tfa-servers
    external: true

services:
  dev-server:
    image: clojure:lein-alpine
    volumes:
      - ./:/app
      - tmp-files:/tmp
    working_dir: /app
    ports:
      - 3001:3001
      - 7001:7001
    networks:
      - tfa-servers
    command: "lein do migratus, ring server-headless"
    user: "1000:1000"
    environment:
      - HOME=/tmp
      - LEIN_JVM_OPTS=-Duser.home=/tmp
      - DATABASE_URL=jdbc:mysql://mysql-server/tfa_db?user=tfa_user&password=secret
